### ISSUE TITLE
use challenge method vs ip validation

### ISSUE THREAD

**Issue by jamesbeedy** [tengu-team/layer-ssl-termination-proxy#10]
Check out how Zappa gets through the domain validation using the challenge method -
 https://github.com/Miserlou/Zappa/blob/master/zappa/letsencrypt.py

Possibly this is a better/less brittle method then using the ip validation method used by https://github.com/cmars/layer-lets-encrypt

@cmars (if you can hear me) how do you feel about ^ ?

**Comment by cmars** [comment]
If I'm reading this correctly, this uses the `dns-01` method in coordination with AWS Route 53. That is very convenient; out-of-band DNS registration is cumbersome, but this would only work on AWS.

There was some discussion around how to best expose cloud-provider specific APIs to charms, would be a good topic to raise on the Juju ML.

**Comment by jamesbeedy** [comment]
"but this would only work on AWS" - true, true, I hadn't taken this into consideration

"There was some discussion around how to best expose cloud-provider specific APIs to charms, would be a good topic to raise on the Juju ML." - ACK

**Comment by merlijn-sebrechts** [comment]
With the new pluggable architecture of the SSL termination proxy, it should be easy to create your own `ssl-termination-fqdn` subordinate which uses a cloud-specific API for automatic DNS.


# Take a look at the following if you want to start hacking on this:


- The interface used to inform the reverseproxy of the correct FQDN: https://github.com/tengu-team/interface-ssl-termination
- A subordinate that implements that relationship to specify the fqdn manually: https://github.com/tengu-team/layer-ssl-termination-fqdn


![](https://raw.githubusercontent.com/tengu-team/layer-ssl-termination-proxy/master/docs/ssl-termination-proxy-example.jpg)
