### ISSUE TITLE
Ip-address change should not requets new certificate

### ISSUE THREAD

**Issue by sebastienpattyn93** [tengu-team/layer-ssl-termination-proxy#15]
While I was testing to connect my kubernetes-cluster to the ssl-termination-proxy, by using a connector charm, I noticed that I went over the rate limit for requests for that domain. Could it be an idea to add an extra check that if just the ip-addresses changed from the new cert-requests, it is not necessary to request a new certificate and just edit the nginx file and restart the service?

**Comment by xannz** [comment]
Implemented in #18.
