### ISSUE TITLE
Add capability to allow for larger uploads

### ISSUE THREAD

**Issue by erik78se** [tengu-team/layer-ssl-termination-proxy#16]
I'm using this layer for "nextcloud" which allows for uploading files.

However, if the files are "larger" than default in nginx, the client sync will fail.

I'm not sure how to best achieve this configuration option in this layer, but the specific configuration option I need to modify is in "/etc/nginx/nginx.conf"

> client_max_body_size 10G;

However, this is a server wide option and would perhaps be better placed in a "per site" basis?

I'm happy to  assist implementing this if you have some suggestion in how to achieve it best.

**Comment by xannz** [comment]
I agree that this should be on a per site basis. Therefore adding custom NGINX config is perhaps better suited as a juju config parameter in the ssl-termination-fqdn charm. 

You would then be able to add custom settings via the fqdn charm:
`juju config fqdn-nextcloud nginx-config="client_max_body_size 10G;"` 
This way we support a whole range of config options at once without it being server wide.

Is this an acceptable approach for you?

**Comment by erik78se** [comment]
That sounds like a very good approach to me.

/Erik

Den mån 14 okt. 2019 11:38Sander Borny <notifications@github.com> skrev:

**Comment by xannz** [comment]
I've pushed the new charms to the edge channel for testing. You can try them out via:
`juju deploy ssl-termination-proxy --channel edge`
`juju deploy ssl-termination-fqdn --channel edge`

You can use 
`juju config ssl-termination-fqdn "nginx-config=client_max_body_size 9G"`
to set the custom nginx config.

**Comment by erik78se** [comment]
Awesome! I'm installing solar panels at the moment for my personal dc, but
once its done I can power on again and test.

juju upgrade-charm should be sufficient?

Den fre 25 okt. 2019 14:23Sander Borny <notifications@github.com> skrev:

**Comment by xannz** [comment]
Apparently only tengu-team members can use the edge channel. I'll have to see if I can grant more people access to the channel.

**Comment by xannz** [comment]
You should now have access to the edge channel. As for testing it out, I'm not confident `juju upgrade-charm` will do the trick with so many changes. I'm planning on testing it out though and if possible add support for the upgrade path as well.

**Comment by erik78se** [comment]
I'm turning on my servers again this weekend, so I should be able to test this soon.

Did you cover yet for the nginx security havoc this week? =D @xannz

**Comment by xannz** [comment]
I'm afraid I'm out of the loop, anything I should know?

**Comment by erik78se** [comment]
I'm about to try it out now, how would you suggest I perform an upgrade on my already existing models running my nextcloud?

juju remove-unit  first?

**Comment by xannz** [comment]
You can try removing the old charm and deploying the new one so you are on bionic or try the juju upgrade-charm route. You'll need to pull from the edge channel for both.

**Comment by xannz** [comment]
Pushed to stable.

**Comment by erik78se** [comment]
I have upgraded with the new revision: 7 and it works. The charms is however stuck for a long time in "Waiting for proxy to register certificate" state. One of my instances has got out form it into "Ready" state after I set a configuration option, but not the other. But the "upgrade-charm" path worked out.

Thanx for a great charm!
