### ISSUE TITLE
Unclear how to deal with a failed Let's Encrypt blocked condition

### ISSUE THREAD

**Issue by paulgear** [tengu-team/layer-ssl-termination-proxy#2]
When I first installed the charm, I neglected to assign a nova floating IP address before deploying, so my VM was not contactable from the public Internet.  The charm went into blocked state (as intended) due to failed Let's Encrypt registration, but it's not clear from the documentation how to get out of this state.

I ended up changing the fqdn config setting, and this was successful in clearing the blocked state, although it led to another bug, which I'll document shortly. I'll also submit a small PR to mention floating IPs in the README.

It would be nice to have clear instructions about what to do if Let's Encrypt registration fails.

**Comment by merlijn-sebrechts** [comment]
Is it a good idea to show the error message from let's encrypt in the blocked status? This will allow operators to debug this without having to dive into the charm.

**Comment by paulgear** [comment]
I'm not sure how much can reasonably be put in the one line of status; I think documentation is probably the most obvious option for starters.  The status message gave me sufficient information to troubleshoot, and I don't really think manual work can be avoided if there's a catastrophic Let's Encrypt error.

**Comment by merlijn-sebrechts** [comment]
I'd really just dump the unformatted let's encrypt output in the status message. Your `juju status` output looks a bit strange when you do that, but I don't think that's an issue since a charm shouldn't stay in a blocked status for long.

**Comment by paulgear** [comment]
Worth a try; happy to give it a go...

**Comment by merlijn-sebrechts** [comment]
The latest version dumps the lets encrypt output and goes into blocked state. This gives you clear instructions how to fix it for most issues.
