### ISSUE TITLE
Support for bionic

### ISSUE THREAD

**Issue by timClicks** [tengu-team/layer-ssl-termination-proxy#21]
This is a really great charm. Is it heavily dependent on xenial?

**Comment by xannz** [comment]
This charm has recently been updated for bionic. It is however still on the edge channel for final testing. I'm waiting until #16 is closed to push it to stable.

**Comment by timClicks** [comment]
Oh fantastic. By the way, I've used the charm as an example in a tutorial I posted today:

https://discourse.jujucharms.com/t/2378

**Comment by xannz** [comment]
Pushed to stable.
