### ISSUE TITLE
Changing FQDN does not update nginx site configuration

### ISSUE THREAD

**Issue by paulgear** [tengu-team/layer-ssl-termination-proxy#4]
Changing the fqdn in the charm configuration (e.g. due to issue #2) does not result in a changed nginx sites-enabled configuration file.  The status displays the new fqdn, but the old site configuration remains in place.  If both the new and old site names point to the same IP address, this results in the name changing in the browser when accessed.

The charm needs a config.changed handler which will adjust the site configuration appropriately.

**Comment by merlijn-sebrechts** [comment]
Should be fixed in the latest version, let us know if this isn't the case.
