### ISSUE TITLE
Add support for using Let's Encrypt staging API endpoint

### ISSUE THREAD

**Issue by paulgear** [tengu-team/layer-ssl-termination-proxy#5]
Sometimes Let's Encrypt registrations fail, ostensibly due to rate limiting.  (Here's a /var/log/letsencrypt/letsencrypt.log extract showing that: http://pastebin.ubuntu.com/24425293/)

In troubleshooting this, it would be nice to be able to hit the Let's Encrypt staging API endpoint to ensure that rate limiting is the real reason.  In the above case it didn't seem to be, because running "letsencrypt certonly -d WWW.EXAMPLE.COM" manually from the juju unit fixed the issue for me.

**Comment by galgalesh** [comment]
I filed this issue against the upstream lets encrypt layer: https://github.com/cmars/layer-lets-encrypt/issues/10

**Comment by paulgear** [comment]
I should have filed it there in the first place.
